(defun print-dotted (lst)
  (cond	((atom lst) (princ lst))
	(t (princ "(")
	   (print-dotted (first lst))
	   (princ " . ")
	   (print-dotted (rest lst))
	   (princ ")"))))

(print-dotted nil)
(terpri)
(print-dotted 'a)
(terpri)
(print-dotted '(a))
(terpri)
(print-dotted '(a b c))
(terpri)
(print-dotted '(a ((b)) c (d b)))
(terpri)
