(defun arr-rot90 (arr)
  (let* ((dims (array-dimensions arr))
	 (rows (car dims)) (cols (cadr dims))
	 (dst (make-array dims :initial-element 0)))
    (do ((row-i 0 (1+ row-i)))
	((<= rows row-i) dst)
	(do ((col-i 0 (1+ col-i)))
	    ((<= cols col-i))
	    (setf (aref dst col-i (- rows row-i 1))
		  (aref arr row-i col-i) )))))

;(setf test #2A((a b c)
;	       (d e f)
;	       (g i k))
